version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
        - '3306:3306'
    volumes:
      - db:/var/run/mysqld
    expose:
      - '3306'
  redis:
    image: redis:6.2
    volumes:
      - 'redis:/data'
  es:
    image: elasticsearch:8.2.0
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - es:/usr/share/elasticsearch/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_POOL: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://localhost:6379/1
      ES_HOST: es
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/myapp'
      - '/myapp/tmp' # don't mount tmp directory
    links:
      - db
      - redis
    working_dir: /chat
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_POOL: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis
      ES_HOST: es
volumes:
  redis:
  db:
  es:
